# Generated by Django 3.1.14 on 2022-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='password',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='room',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
